version: 2

models:
  - name: stg_telegram_messages
    description: "Staging view that cleans raw.telegram_messages for downstream use. Adds helpful boolean flags."
    columns:
      - name: id
        description: "Original Telegram message ID (per chat)."
        tests:
          - not_null
      - name: chat_id
        description: "Telegram chat/channel numeric ID."
        tests:
          - not_null
      - name: channel
        description: "Human-readable channel username or title."
        tests:
          - not_null
      - name: date
        description: "UTC timestamp the message was sent."
        tests:
          - not_null
      - name: message_text
        description: "Cleaned text payload of the message."

  - name: dim_channels
    description: "Dimension table containing unique Telegram channels with surrogate key."
    columns:
      - name: channel_id
        description: "Surrogate key for each channel."
        tests:
          - unique
          - not_null
      - name: channel
        description: "Channel username / title."
        tests:
          - not_null
      - name: chat_id
        description: "Telegram numeric chat ID."
        tests:
          - unique
          - not_null

  - name: dim_dates
    description: "Date dimension spanning min/max dates found in message data."
    columns:
      - name: date_id
        description: "The actual calendar date (PK)."
        tests:
          - unique
          - not_null
      - name: year
        description: "4-digit calendar year."
      - name: month
        description: "Month number (1-12)."
      - name: day
        description: "Day of month."

  - name: fct_messages
    description: "Fact table containing one row per Telegram message with FKs to dimensions and analytic flags."
    columns:
      - name: message_id
        description: "Original Telegram message ID."
        tests:
          - unique
          - not_null
      - name: channel_id
        description: "FK to dim_channels."
        tests:
          - relationships:
              to: ref('dim_channels')
              field: channel_id
      - name: date_id
        description: "FK to dim_dates."
        tests:
          - relationships:
              to: ref('dim_dates')
              field: date_id
      - name: message_text
        description: "Cleaned text of the message."
      - name: media
        description: "Boolean indicating media presence."
      - name: has_url
        description: "Boolean indicating URL presence."
      - name: has_hashtag
        description: "Boolean indicating hashtag presence."
      - name: has_mention
        description: "Boolean indicating mention presence."
