name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: telegram
          POSTGRES_PASSWORD: Seyaman@123
          POSTGRES_DB: telegram_dw
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure dbt postgres adapter is available for `dbt build`
          pip install dbt-postgres

      - name: Set env vars for DB
        run: |
          echo "POSTGRES_HOST=localhost" >> $GITHUB_ENV
          echo "POSTGRES_PORT=5432" >> $GITHUB_ENV
          echo "POSTGRES_USER=telegram" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=Seyaman@123" >> $GITHUB_ENV
          echo "POSTGRES_DB=telegram_dw" >> $GITHUB_ENV

      - name: Load raw data into PostgreSQL
        run: python src/load_raw.py

      - name: Run dbt build & test
        run: |
          dbt deps
          dbt build --profiles-dir dbt

      - name: Generate dbt docs
        run: dbt docs generate --profiles-dir dbt

